//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SopMessageView.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SopMessageView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 0000(0000)  00 C9 31 32 33 34 35 36 37 38 39 30 31 32 33 34   **12345678901234
        ///0010(0016)  35 36 39 33 30 31 00 00 00 00 00 00 00 00 00 00   569301**********
        ///0020(0032)  00 00 00 00 00 00 0A 70 13 6C 0A 70 12 3A 00 01   *******p*l*p*:**
        ///0030(0048)  04 27 00 00 00 00 00 46 45 53 30 30 00 00 00 00   *&apos;*****FES00****
        ///0040(0064)  39 33 30 31 31 31 30 30 31 37 31 33 45 38 30 39   930111001713E809
        ///0050(0080)  00 00 00 00 00 00 00 00 7D 00 00 00 00 46 45 53   ********}****FES
        ///0060(0096)  30 30 32 34 31 32 39 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;MessageMap&gt;
        ///  &lt;Message&gt;
        ///    &lt;Parameter Name=&quot;Trade&quot; Value=&quot;轧帐检查账户配置&quot;/&gt;
        ///    &lt;Parameter Name=&quot;TranCode&quot; Value=&quot;E809&quot;/&gt;
        ///    &lt;Parameter Name=&quot;Service&quot; Value=&quot;SPD_IPPSRV1&quot;/&gt;
        ///    &lt;Parameter Name=&quot;MessageLenField&quot; Value=&quot;SHJBCD&quot;/&gt;
        ///    &lt;Parameter Name=&quot;TradeDataCategory&quot; Value=&quot;i&quot;/&gt;
        ///    &lt;Parameter Name=&quot;TradeDataLenField&quot; Value=&quot;COMMLN&quot;/&gt;
        ///    &lt;Parameter Name=&quot;ErrorCheckField&quot; Value=&quot;PTCWDH&quot;/&gt;
        ///    &lt;Parameter Name=&quot;ErrorCodeField&quot; Value=&quot;PTCWDH&quot;/&gt;
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string rcdFile {
            get {
                return ResourceManager.GetString("rcdFile", resourceCulture);
            }
        }
    }
}
